passing tests: testPackageJsonWithoutVersion, testPackageJsonWithStableVersion, testPackageJsonWithUnstableVersion

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -8,13 +8,17 @@ stable_version="0.10.18"
 source $bp_dir/bin/common.sh
 
 # Output debug info on exit
-trap cat_npm_debug_log EXIT
+# trap cat_npm_debug_log EXIT
 
 status "Downloading node version $stable_version"
 download_and_install_node $stable_version
 
 # Is a node version specified in package.json?
-requested_version=$(cat $build_dir/package.json | node $bp_dir/vendor/json engines.node 2>/dev/null)
+determine_requested_version() {
+  v=$(cat $build_dir/package.json | node $bp_dir/vendor/json engines.node 2>/dev/null)
+  if [ $? == 0 ]; then echo $v; fi
+}
+requested_version=$(determine_requested_version)
 
 # Give a warning if no node engine is specified
 if ! test $requested_version; then
@@ -23,32 +27,32 @@ if ! test $requested_version; then
   echo "WARNING: No node version specified in package.json, see:" | indent
   echo "https://devcenter.heroku.com/articles/nodejs-support#versions" | indent
   echo
+  status "Using latest stable node version $stable_version"
 
 else
   # Does the already-downloaded stable version of node satisfy the requested version?
-  default_satisfies=$(node $bp_dir/vendor/semver/bin/semver -v $stable_version -r "$requested_version" || echo "")
+  default_satisfies=$(node $bp_dir/vendor/semver/bin/semver -v "${stable_version}" -r "${requested_version}" || echo "")
 
-  if ! test $default_satisfies; then
-    status "Using node version $stable_version"
+  if test $default_satisfies; then
+    status "Using latest stable node version $stable_version"
   else
     # Find all available versions from nodejs.org/dist
-    available_versions=""
-    for version in query_all_versions; do
-      available_versions="${available_versions} -v \"${version}\""
-    done
+    args=""
+    for version in $(query_all_versions); do args="${args} -v \"${version}\""; done
+    args="${args} -r \"${requested_version}\""
 
     # Determine which available versions satisfy the requested version
     # https://github.com/isaacs/node-semver/blob/master/bin/semver
-    evaluated_versions=$(node $bp_dir/vendor/semver/bin/semver $available_versions -r "$requested_version" || echo "")
+    evaluated_versions=$(eval node $bp_dir/vendor/semver/bin/semver ${args} || echo "")
 
     # Use the latest of the evaluated versions
-    node_version=$("$evaluated_versions" | tail -n 1)
+    node_version=$(echo $evaluated_versions | tail -n 1)
 
     if test $node_version; then
       status "Using node version $node_version"
       download_and_install_node $node_version
     else
-      error "Requested node version ${requested_version} not found among available versions: ${available_versions}"
+      error "Requested node version ${requested_version} not found among available versions on nodejs.org/dist"
     fi
   fi
 fi
@@ -58,16 +62,18 @@ cache_store_dir="$cache_dir/node_modules/$node_version"
 cache_target_dir="$build_dir/node_modules"
 
 # Restore node_modules from cache, if present
-if [ -d $cache_store_dir ]; then
-  status "Restoring node_modules cache"
-  if [ -d $cache_target_dir ]; then
-    cp -r $cache_store_dir/* $cache_target_dir/
-  else
-    cp -r $cache_store_dir $cache_target_dir
-  fi
-  status "Pruning any unused dependencies"
-  npm prune
-fi
+# if [ -d $cache_store_dir ]; then
+#   status "Restoring node_modules cache"
+#   if [ -d $cache_target_dir ]; then
+#     cp -r $cache_store_dir/* $cache_target_dir/
+#   else
+#     cp -r $cache_store_dir $cache_target_dir
+#   fi
+#   status "Pruning any unused dependencies"
+#   npm prune
+# fi
+
+cd $build_dir
 
 # Install dependencies
 status "Installing dependencies"
@@ -75,12 +81,12 @@ npm install --production
 npm rebuild
 
 # Cache node_modules for future builds
-if [ -d $cache_target_dir ]; then
-  status "Caching node_modules for future builds"
-  rm -rf $cache_store_dir
-  mkdir -p $(dirname $cache_store_dir)
-  cp -r $cache_target_dir $cache_store_dir
-fi
+# if [ -d $cache_target_dir ]; then
+#   status "Caching node_modules for future builds"
+#   rm -rf $cache_store_dir
+#   mkdir -p $(dirname $cache_store_dir)
+#   cp -r $cache_target_dir $cache_store_dir
+# fi
 
 # Update the PATH
 status "Building runtime environment"
