stderr useful message on detect failure

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -2,8 +2,9 @@
 # bin/detect <build-dir>
 
 if [ -f $1/package.json ]; then
-  echo "Node.js"
+  echo 'Node.js'
   exit 0
 fi
 
+>&2 echo 'Node.js: package.json not found in application root'
 exit 1
