Switch to new metrics api (#1470)
* Copy `builddata` script from classic Python buildpack

* Rewrite `report` script to output JSON data

* Cleanup script capture and stop emitting `$BUILDPACK_LOG_FILE`

* Switch to new API from `builddata.sh`

* Remove some of the old metrics unit tests

* Add new helpers for validating metrics

* Fix up metrics tests

* Fix testNpmCiFallback test

* Fix testYarnBuildMetaData and testPnpmBuildMetaData which should only track the bundled npm version

* Fix testBinReportEmptyDirectory, testBinReportSuccess, testBinReportScriptsWithQuotes, testBinReportYarn. Removed redundant tests and simplified ones that check `bin/report`.

* Fix testNpmCiFallback and testNpmVersionIncompatible which don't work right unless `monitor` wraps the actual npm install command and error handler

* Fix remaining tests that are missing the required `cache_dir` arg and using a better assertion

* Add method to read metrics from the current build

* Use `get_current` instead of `get_previous`

* Update CHANGELOG.md

* Update CHANGELOG.md to note rollback

* Remove unused `metadata.sh` script

* Update calls to use `build_data::current_unix_realtime`

* More cleanup of unused functionality

* Use more robust script replacement

* Suggested change from dzuelke to remove unnecessary `tr` call

* Update lib/builddata.sh

Co-authored-by: Richard Schneeman <richard.schneeman+foo@gmail.com>
Signed-off-by: Colin Casey <casey.colin@gmail.com>

* Update test helper

* Remove legacy file code in `get_current` function as that doesn't apply

* Remove legacy cached build-data

* Update bin/compile

Co-authored-by: Ed Morley <501702+edmorley@users.noreply.github.com>
Signed-off-by: Colin Casey <casey.colin@gmail.com>

---------

Signed-off-by: Colin Casey <casey.colin@gmail.com>
Co-authored-by: Richard Schneeman <richard.schneeman+foo@gmail.com>
Co-authored-by: Ed Morley <501702+edmorley@users.noreply.github.com>

diff --git a/test/unit b/test/unit
--- a/test/unit
+++ b/test/unit
@@ -23,46 +23,6 @@ print_number_args() {
   echo "$#"
 }
 
-testMonitorMemory() {
-  local mem_output=$(mktemp)
-  local stdout_capture=$(mktemp)
-
-  monitor_memory_usage $mem_output echo "this is a test" > /dev/null
-  assertTrue "should use less than 2mb" "[[ $(cat $mem_output) -lt 2 ]]"
-
-  monitor_memory_usage $mem_output use_memory
-  assertTrue "should use more than 10mb" "[[ $(cat $mem_output) -gt 10 ]]"
-
-  monitor_memory_usage $mem_output print_args --foo --bar="baz lol hi" > $stdout_capture
-  assertTrue "should use less than 2mb" "[[ $(cat $mem_output) -lt 2 ]]"
-  assertTrue "should output 2 lines" "[[ $(wc -l < $stdout_capture) -eq 2 ]]"
-  assertEquals "first line" "--foo" "$(head -n 1 $stdout_capture)"
-  assertEquals "second line" "--bar=baz lol hi" "$(tail -n 1 $stdout_capture)"
-}
-
-testMonitor() {
-  local out
-
-  # test that we're forwarding empty arguments correctly
-  out=$(monitor "command-name" print_number_args "" "" "" "")
-  assertEquals "4" "$out"
-
-  # Don't expand *
-  out=$(monitor "command-name" echo "*")
-  assertEquals "*" "$out"
-
-  out=$(monitor "command-name" print_number_args "*")
-  assertEquals "1" "$out"
-
-  # # Don't split arguments with a space
-  out=$(monitor "command-name" echo "1  3")
-  assertEquals "1  3" "$out"
-
-  # # Test everything with an empty arg
-  out=$(monitor "command-name" echo 1 "" 2 "3   4" "*")
-  assertEquals "1  2 3   4 *" "$out"
-}
-
 testOutput() {
   local stdout
 
@@ -166,119 +126,6 @@ testKeyValueNoFile() {
   assertEquals "$(kv_get $space key)" ""
   assertEquals "$(kv_keys $space)" ""
   assertEquals "$(kv_list $space)" ""
-}
-
-testBuildData() {
-  local cache_dir
-
-  # prevent state from previous tests from polluting this one
-  meta_force_clear
-
-  cache_dir=$(mktemp -d)
-
-  meta_init "$cache_dir"
-  meta_setup
-
-  meta_set "test" "foo"
-  assertEquals "test=foo" "$(log_meta_data)"
-
-  meta_set "test" "different-foo"
-  assertEquals "test=different-foo" "$(log_meta_data)"
-
-  meta_set "foo" "value with spaces"
-  assertEquals "foo=\"value with spaces\" test=different-foo" "$(log_meta_data)"
-
-  # values are printed with the keys sorted alphabetically
-  # this isn't required, and this test serves as documentation
-  meta_set "a" "this should come first"
-  assertEquals "a=\"this should come first\" foo=\"value with spaces\" test=different-foo" "$(log_meta_data)"
-
-  # dates generated by running `nowms; sleep 10; nowms`
-  meta_time "time" "1545178120033" "1545178130043"
-  assertEquals "10.010" "$(meta_get time)"
-
-  # dates generated by running `nowms; sleep 1; nowms`
-  meta_time "time" "1545178503025" "1545178504027"
-  assertEquals "1.002" "$(meta_get time)"
-
-  # dates generated by running `nowms; sleep 30; nowms`
-  meta_time "time" "1545178521204" "1545178551206"
-  assertEquals "30.002" "$(meta_get time)"
-}
-
-setupMetadata() {
-  local cache_dir="$1"
-  # create the data store
-  meta_init "$cache_dir"
-  meta_setup
-  # store some data
-  meta_set "foo" "bar"
-}
-
-testBuildDataInitIdempotent() {
-  local cache_dir temp
-
-  cache_dir="$(mktemp -d)"
-
-  # prevent state from previous tests from polluting this one
-  meta_force_clear
-
-  # Set up the cache directory. This is run in a subshell so that the generated state
-  # doesn't pollute this test. We only want the state on the disk.
-  temp=$(setupMetadata "$cache_dir")
-
-  # To test this, let's make sure that get-ing "foo" returns nothing
-  assertEquals "" "$(meta_get "foo")"
-
-  # init the data store
-  meta_init "$cache_dir"
-
-  # The datastore created in the subshell should now work
-  assertEquals "bar" "$(meta_get "foo")"
-
-  # There should be no previous data
-  assertEquals "" "$(meta_prev_get "foo")"
-}
-
-testBuildDataPreviousBuild() {
-  local cache_dir=$(mktemp -d)
-
-  # the first time, there will be no previous build file
-  meta_init "$cache_dir"
-  meta_setup
-  assertContains "$BUILD_DATA_FILE" "nodejs"
-  assertContains "$PREVIOUS_BUILD_DATA_FILE" "nodejs-prev"
-  assertFileExists "$BUILD_DATA_FILE"
-
-  # set a value in the build data file
-  meta_set "test" "foo"
-  assertFileContains "test=foo" "$BUILD_DATA_FILE"
-  assertFileDoesNotExist "$PREVIOUS_BUILD_DATA_FILE"
-
-  assertEquals "$(meta_get test)" "foo"
-  assertEquals "$(meta_prev_get test)" ""
-
-  # the second time this is called (cache restored)
-  # there will be a previous build file
-  meta_init "$cache_dir"
-  meta_setup
-  assertFileExists "$BUILD_DATA_FILE"
-  assertFileExists "$PREVIOUS_BUILD_DATA_FILE"
-
-  # the data stored in the previous build should now be in the second file
-  assertFileNotContains "test=foo" "$BUILD_DATA_FILE"
-  assertFileContains "test=foo" "$PREVIOUS_BUILD_DATA_FILE"
-  assertEquals "$(meta_get test)" ""
-  assertEquals "$(meta_prev_get test)" "foo"
-  meta_set "test" "bar"
-
-  # doing it once more does not result in an error
-  meta_init "$cache_dir"
-  meta_setup
-  assertFileExists "$BUILD_DATA_FILE"
-  assertFileExists "$PREVIOUS_BUILD_DATA_FILE"
-  assertEquals "$(meta_prev_get test)" "bar"
-  assertEquals "$(meta_get test)" ""
 }
 
 testWebConcurrencyDoesNotOverrideManualValue() {
@@ -450,6 +297,115 @@ testFeaturesNoInit() {
   assertEquals "running features_get without init should return false" "false" "$(features_get "test-name-3")"
 }
 
+testAssertMetricsBasicQueries() {
+  local cache_dir=$(mktemp -d)
+  local metrics_dir="${cache_dir}/build-data"
+  local metrics_file="${metrics_dir}/nodejs.json"
+  
+  # Create the metrics directory and file
+  mkdir -p "$metrics_dir"
+  
+  # Test basic jq queries
+  echo '{"package_manager": "npm", "build_time": 1.234, "cache_status": "not-found"}' > "$metrics_file"
+  assertMetrics "$cache_dir" <<-EOF
+    select(.package_manager == "npm")
+    select(.build_time | type == "number")
+    select(.cache_status == "not-found")
+EOF
+  
+  # Cleanup
+  rm -rf "$cache_dir"
+}
+
+testAssertMetricsMissingArgument() {
+  local error_output
+  error_output=$(assertMetrics <<-EOF 2>&1 || true
+EOF
+)
+  if ! echo "$error_output" | grep -q "cache_dir argument is required"; then
+    fail "assertMetrics should have failed with appropriate error message for missing argument"
+  fi
+}
+
+testAssertMetricsNonExistentFile() {
+  local cache_dir=$(mktemp -d)
+  local error_output
+  error_output=$(assertMetrics "$cache_dir" <<-EOF 2>&1 || true
+    select(.package_manager == "npm")
+EOF
+)
+  if ! echo "$error_output" | grep -q "Metrics file not found"; then
+    fail "assertMetrics should have failed with appropriate error message for non-existent file"
+  fi
+  
+  # Cleanup
+  rm -rf "$cache_dir"
+}
+
+testAssertMetricsInvalidJqQuery() {
+  local cache_dir=$(mktemp -d)
+  local metrics_dir="${cache_dir}/build-data"
+  local metrics_file="${metrics_dir}/nodejs.json"
+  
+  # Create the metrics directory and file
+  mkdir -p "$metrics_dir"
+  echo '{"package_manager": "npm"}' > "$metrics_file"
+  
+  local error_output
+  error_output=$(assertMetrics "$cache_dir" <<-EOF 2>&1 || true
+    select(.nonexistent == "value")
+EOF
+)
+  if ! echo "$error_output" | grep -q "jq query failed"; then
+    fail "assertMetrics should have failed with appropriate error message for invalid jq query"
+  fi
+  
+  # Cleanup
+  rm -rf "$cache_dir"
+}
+
+testAssertMetricsUncheckedKeys() {
+  local cache_dir=$(mktemp -d)
+  local metrics_dir="${cache_dir}/build-data"
+  local metrics_file="${metrics_dir}/nodejs.json"
+  
+  # Create the metrics directory and file
+  mkdir -p "$metrics_dir"
+  echo '{"package_manager": "npm", "build_time": 1.234, "cache_status": "not-found"}' > "$metrics_file"
+  
+  local error_output
+  error_output=$(assertMetrics "$cache_dir" <<-EOF 2>&1 || true
+    select(.package_manager == "npm")
+EOF
+)
+  if ! echo "$error_output" | grep -q "keys in the metrics file were not checked: \[build_time,cache_status\]"; then
+    fail "assertMetrics should have failed with appropriate error message for unchecked keys"
+  fi
+  
+  # Cleanup
+  rm -rf "$cache_dir"
+}
+
+testAssertMetricsAllKeysChecked() {
+  local cache_dir=$(mktemp -d)
+  local metrics_dir="${cache_dir}/build-data"
+  local metrics_file="${metrics_dir}/nodejs.json"
+  
+  # Create the metrics directory and file
+  mkdir -p "$metrics_dir"
+  echo '{"package_manager": "npm", "build_time": 1.234, "cache_status": "not-found"}' > "$metrics_file"
+  
+  # Should pass when all keys are checked
+  assertMetrics "$cache_dir" <<-EOF
+    select(.package_manager == "npm")
+    select(.build_time | type == "number")
+    select(.cache_status == "not-found")
+EOF
+  
+  # Cleanup
+  rm -rf "$cache_dir"
+}
+
 BP_DIR="$(pwd)"
 
 # the modules to be tested
@@ -463,7 +419,6 @@ source "$(pwd)"/lib/monitor.sh
 source "$(pwd)"/lib/output.sh
 source "$(pwd)"/lib/kvstore.sh
 source "$(pwd)"/lib/features.sh
-source "$(pwd)"/lib/metadata.sh
 source "$(pwd)"/profile/WEB_CONCURRENCY.sh
 
 # testing utils
